// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentRun.Server.Data;

#nullable disable

namespace StudentRun.Server.Data.Migrations
{
    [DbContext(typeof(StudentRunContext))]
    [Migration("20251104050541_ProgressTablesInit")]
    partial class ProgressTablesInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentRun.Server.Models.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Milestone")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("prize_pkey");

                    b.ToTable("prize", (string)null);
                });

            modelBuilder.Entity("StudentRun.Server.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("first_name");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("LastName")
                        .HasColumnType("character varying")
                        .HasColumnName("last_name");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("student_pkey");

                    b.HasIndex("TeacherId");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("StudentRun.Server.Models.StudentPrize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("PrizeId")
                        .HasColumnType("integer");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("studentPrize_pkey");

                    b.HasIndex("PrizeId");

                    b.HasIndex("StudentId");

                    b.ToTable("studentPrize", (string)null);
                });

            modelBuilder.Entity("StudentRun.Server.Models.StudentRunMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Card")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("studentRunMetric_pkey");

                    b.HasIndex("StudentId");

                    b.ToTable("studentRunMetric", (string)null);
                });

            modelBuilder.Entity("StudentRun.Server.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying")
                        .HasColumnName("first_name");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("teacher_pkey");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("StudentRun.Server.Models.Student", b =>
                {
                    b.HasOne("StudentRun.Server.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("student_teacher_id_teacher_id_fk");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentRun.Server.Models.StudentPrize", b =>
                {
                    b.HasOne("StudentRun.Server.Models.Prize", "Prize")
                        .WithMany("StudentPrizes")
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentRun.Server.Models.Student", "Student")
                        .WithMany("StudentPrizes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studentPrize_id_student_id_fk");

                    b.Navigation("Prize");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentRun.Server.Models.StudentRunMetric", b =>
                {
                    b.HasOne("StudentRun.Server.Models.Student", "Student")
                        .WithMany("StudentRunMetrics")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studentRunMetric_id_teacher_id_fk");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentRun.Server.Models.Prize", b =>
                {
                    b.Navigation("StudentPrizes");
                });

            modelBuilder.Entity("StudentRun.Server.Models.Student", b =>
                {
                    b.Navigation("StudentPrizes");

                    b.Navigation("StudentRunMetrics");
                });

            modelBuilder.Entity("StudentRun.Server.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
