@domain_Url = https://localhost:5000/api

GET {{domain_Url}}/teacher
Accept: application/json

###

@id=1
GET {{domain_Url}}/teacher/{{id}}/students
Accept: application/json

###

GET {{domain_Url}}/student
Accept: application/json

###

@id=2
GET {{domain_Url}}/student/{{id}}
Accept: application/json

###
